services:
  app:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    volumes:
      - .:/app
      - /app/node_modules

  app-prod:
    profiles: ["prod"]
    build:
      context: .
      target: prod
    ports:
      - "8080:80"

