name: Publish Canary

on:
  workflow_dispatch:
    inputs:
      preid:
        description: "Pre-release id (default 'canary')"
        required: false
        default: "canary"

jobs:
  canary:
    name: Publish canary to npm
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_OPTIONAL: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.5.0
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies (allow peer mismatch)
        run: npm ci --legacy-peer-deps

      - name: Ensure Rollup binary (Linux)
        if: runner.os == 'Linux'
        run: |
          set -e
          ROLLUP_VERSION=$(node -p "require('./package-lock.json').packages['node_modules/rollup']?.version || ''")
          echo "Detected rollup version: ${ROLLUP_VERSION}"
          if [ -n "$ROLLUP_VERSION" ]; then
            npm i -D --no-audit --no-fund "@rollup/rollup-linux-x64-gnu@${ROLLUP_VERSION}"
          else
            echo "Rollup not found in package-lock.json; skipping explicit binary install"
          fi

      - name: Compute canary version
        id: ver
        shell: bash
        run: |
          set -e
          PREID="${{ github.event.inputs.preid || 'canary' }}"
          CANARY_VERSION=$(node -e "const pkg=require('./package.json');const base=pkg.version.split('-')[0];const sha=process.env.GITHUB_SHA.slice(0,7);const dt=new Date().toISOString().replace(/[-:TZ:.]/g,'').slice(0,12);console.log(`${base}-${PREID}.${dt}.${sha}`)")
          echo "Will publish version: $CANARY_VERSION"
          echo "CANARY_VERSION=$CANARY_VERSION" >> "$GITHUB_ENV"
          # Do not commit the version change, only mutate the workspace package.json
          npm version "$CANARY_VERSION" --no-git-tag-version

      - name: Build library
        run: npm run build

      - name: Publish to npm with canary dist-tag
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CLOVER_IIIF_NPM_TOKEN }}
        run: |
          npm publish --tag canary --access public
